### ISSUE TITLE
Prod build is still not happening at all :( 

### ISSUE THREAD

**Issue by Chethannp** [uploadcare/ngx-uploadcare-widget#22]
![2018_08_09_22_35_28_npm](https://user-images.githubusercontent.com/7566931/43947000-742f9398-9ca4-11e8-8f90-7d376595889b.png)

Team, Please let us know if it is possible to resolve this by today else we will think about an alternative solutions as your updates are not helping us in any which ways and is killing most of our time in waiting for your inputs.

**Comment by bautrukevich** [comment]
@ZNick1982 please, look at this

**Comment by Chethannp** [comment]
Let me know what details you want. Fyi.. UcwidgetModule is still failing so tried follow methods posted in #10, This was at least working fine till last week not sure what happened now even this is failing :(

**Comment by Chethannp** [comment]
@ZNick1982  - Can you atleast tell me what needs to be done ??? #10 was working fine not sure what happened... Do you want to join a skype / hangouts call let me know,  I think this interaction has now gone past 2+ months and we do not have a proper plugin from your team yet.

**Comment by Chethannp** [comment]
@ZNick1982 - can you respond to this thread asap please.

**Comment by ZNick1982** [comment]
Hi @Chethannp . 
Just started to investigate this error. Will write back with updates.

**Comment by Chethannp** [comment]
@ZNick1982  - In the mean while can you please tell me how to import this into our project should I still follow #10 method?? I am using lazyloading.

**Comment by Chethannp** [comment]
I am doing it like this ..
Followed #10 on commenting UcwidgetModule and UcWidgetCustomModule.

**Created a shared module folder call ComponentsModule.**

import { NgModule } from '@angular/core';
**import { UcWidgetComponent } from 'ngx-uploadcare-widget';**
import { ElasticHeaderDirective } from '../directives/elastic-header/elastic-header';

@NgModule({
	declarations: [**UcWidgetComponent**, ElasticHeaderDirective],
	imports: [],
	exports: [**UcWidgetComponent**, ElasticHeaderDirective]
}) 
export class ComponentsModule {} 

**Imported in my home page modules file**
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { HomePage } from './home';

//Shared Module
**import { ComponentsModule } from '../../components/components.module';**
import { ElasticHeaderModule } from "ionic2-elastic-header/dist";

@NgModule({
  declarations: [
    HomePage,
  ],
  imports: [
    IonicPageModule.forChild(HomePage),
    **ComponentsModule**,
    ElasticHeaderModule
  ],
})
export class HomePageModule {}

**Comment by ZNick1982** [comment]
No, I think this steps will not help. 
This is another kind of error.
Trying to figure out what exactly ionic wants.

**Comment by Chethannp** [comment]
ok. when you figure out and fix it please also walk me through steps to use it in my project pls pls pls.  and by gods grace I hope you get the fix asap ,....!

**Comment by ZNick1982** [comment]
@Chethannp Looks like I found the issue and fixed this in pr: https://github.com/uploadcare/ngx-uploadcare-widget/pull/23
Meanwhile pr on the review you can do following for your solution:
1. Replace folder `your_project/node_modules/ngx_uploadcare_widget/release` with `release` from pr.
2. Replace file `your_project/node_modules/ngx_uploadcare_widget/package.json` with same file from pr

Try to rebuild your solution.

Regarding the correct usage of widget.
1. You need to to import module:
`import { UcWidgetModule } from 'ngx-uploadcare-widget';`
and add this to your module as in example:
```
@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    UcWidgetModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```
2. Just use the component in the your app:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      About
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ngx-uploadcare-widget>
  </ngx-uploadcare-widget>

</ion-content>
```
Hope this helps.

**Comment by ZNick1982** [comment]
Ok,
Please write me back with results.

**Comment by Chethannp** [comment]
Just downloaded the branch v_1.1.3_typings_fix and trying it out on a fresh project. In the meanwhile can you please look into the safari issue

**Comment by Chethannp** [comment]
@ZNick1982  - It is still failing..

![2018_08_09_22_35_28_npm](https://user-images.githubusercontent.com/7566931/43953735-91448f66-9cb7-11e8-9bfd-936b00e90074.png)


Should I create  a shared module declare it there and then import it in the lazy loaded list page?

**Comment by ZNick1982** [comment]
let me check on my laptop

**Comment by ZNick1982** [comment]
Looks like you did not replace the package.json from the pr.
Since the typings still looks to `ngx-uploadcare-widget/release/src/` folder.

**Comment by Chethannp** [comment]
No I did clone of the entire branch to my local.

**Comment by ZNick1982** [comment]
Can you please check again.
Since the typing should be use `release` folder:
![image](https://user-images.githubusercontent.com/5286366/43955150-99824d40-9ca7-11e8-8ab1-9f8ae3fb8e11.png)

**Comment by Chethannp** [comment]
I am doing it again.

**Comment by Chethannp** [comment]
I think the issue is resolved. Will any how confirm in 2 hours.

**Comment by Chethannp** [comment]
@ZNick1982 -  it is still failing

![2](https://user-images.githubusercontent.com/7566931/43958881-90329d62-9cca-11e8-8e13-811776a6f5fd.png)

![2018_08_10_18_23_04_package json_app_visual_studio_code](https://user-images.githubusercontent.com/7566931/43958892-95611980-9cca-11e8-9d1d-d9c7edc52135.png)

**Comment by ZNick1982** [comment]
@Chethannp Its still not version from pr. Can you please check it again?
The typings field should be: `"typings": "release/index.d.ts",`

**Comment by Chethannp** [comment]
Can you please send me the zip folder here. my email id is chats1986@gmail.com. Please I am requesting you.

**Comment by ZNick1982** [comment]
@Chethannp We just released new version 1.1.3 of library in npm.
Can you run `npm update` on your projects.
And try to rebuild.

**Comment by Chethannp** [comment]
Doing it now.

**Comment by Chethannp** [comment]
Fantastic work @ZNick1982  - It fixed the build issue!!!! Thanks a lot man.

**Comment by Chethannp** [comment]
Will not bug guys anymore if you can help me with the safari issue. The widget is not seen in safari browser instead white screen is displayed may be css's are not being applied or something could you please try to reproduce this on your system.

**Comment by ZNick1982** [comment]
@Chethannp Thanks!
I can check Safari issue on the next week just after I've got my Mac back.
Now I work on Windows laptop.

**Comment by bautrukevich** [comment]
@Chethannp on Safari MacOS? Or iOS? Can we close this issue?

**Comment by bautrukevich** [comment]
On Safari MacOS demo works fine

**Comment by bautrukevich** [comment]
Also, I check demo on iOS Simulator in Safari iOS — works fine.
